### ISSUE TITLE
Website "How to set it up" is wrong

### ISSUE THREAD

**Issue by birdwing** [stevenvachon/jquery.wrecker#2]
On your website: https://www.svachon.com/blog/wrecker-responsive-equal-height-columns-and-rows/

In the __How to set it up__ section you give this code snippet as an example
```javascript
$(function(){
	$("#container").wrecker({
		// options
		itemSelector : ".item",
		maxColumns : 4,
		responsiveColumns : {
			// windowMaxWidth : columns
			// windowMaxWidth order and values should match those in your responsive CSS
			{1024 : 3},
			{800  : 2},
			{640  : 1}
		}
	});
});
```

You are showing to create respnsiveColumns as an opject with curly brackets {} instead of an array with square brackets [].

If someone were to use the above code they would get an invalid property error.

**Comment by stevenvachon** [comment]
Thanks! Fixed.
